#My Project
myName = input("What's your name?: ")
print("Hi", myName)
favFood = input("What's your favorite food?: ")
favMusic = input("What's your favorite music?: ")
print(myName, "you should eat", favFood, "while listening to", favMusic)

#Exercises
myName = input("What's your name?: ")
myAge = input("How old are you? :")
print("Gee, that's REALLY OLD")
replit = input("Do you like Replit?")
print("OF COURSE YOU DO!")
print()
print("So, you are")
print(myName)
print("and are the ripe old age of")
print(myAge)
print("and clearly think that Replit is")
print(replit)


my_variable = input("WHO_GOES_THERE?")
print(my_variable)


myGrandma = input("How's your Grandma doing? 😘 ")
print(myGrandma)

myLunch = input("What are you having for lunch? ")
print("Hmm, it sounds like you really should just order")
print(myLunch)
print("as soon as possible!")

print("Definitely not a Phishing Scam")
print()
myName = input("What is your name?")
print("Thanks for logging in")
print(myName)
cardNumber = input("What is your credit card number?")
print("Thanks, I definitely won't put")
print(cardNumber)
print("into Amazon and order anything weird")
print()
print("Promise")
maidenName = input("What is your Mother's maiden name? ")
print()
print("That's cool, I just wanted to know that")
print(maidenName)
print("was your Mum's maiden name. Not because the bank requested it or anything, honest.")